[package]
name = "mjolnir-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
mjolnir-core.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
aes-gcm.workspace = true
pqcrypto-dilithium.workspace = true
pqcrypto-kyber.workspace = true
pqcrypto-traits.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
hex.workspace = true

[dev-dependencies]
