[package]
name = "mjolnir-signatures"
version.workspace = true
edition.workspace = true

[dependencies]
mjolnir-core.workspace = true
mjolnir-crypto.workspace = true
yara-x.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
dashmap.workspace = true
chrono.workspace = true
uuid.workspace = true
